services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Infrastructure/Persistence/Entity/'
            - '../src/Application/DTO/'
            - '../src/Domain/'
            - '../src/Kernel.php'

    # Repository binding
    App\Domain\Repository\GameRepositoryInterface:
        class: App\Infrastructure\Persistence\Repository\DoctrineGameRepository

    # Services
    App\Domain\Service\MinimaxStrategy: ~

    # Use cases
    App\Application\UseCase\StartGameUseCase: ~
    App\Application\UseCase\MakeMoveUseCase: ~
    App\Application\UseCase\GetGameStatusUseCase: ~

    # Controller
    App\Presentation\Controller\GameController:
        arguments:
            $startGameUseCase: '@App\Application\UseCase\StartGameUseCase'
            $makeMoveUseCase: '@App\Application\UseCase\MakeMoveUseCase'
            $getGameStatusUseCase: '@App\Application\UseCase\GetGameStatusUseCase'
            $minimaxStrategy: '@App\Domain\Service\MinimaxStrategy'
