services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Domain Repository Interface Binding
    App\Domain\Repository\GameRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\DoctrineGameRepository

    # Use Cases
    App\Application\UseCase\StartGameUseCase:
        arguments:
            $gameRepository: '@App\Domain\Repository\GameRepositoryInterface'

    App\Application\UseCase\MakeMoveUseCase:
        arguments:
            $gameRepository: '@App\Domain\Repository\GameRepositoryInterface'

    App\Application\UseCase\GetGameStatusUseCase:
        arguments:
            $gameRepository: '@App\Domain\Repository\GameRepositoryInterface'
